#  ╔════════════════════════════════════════════════════════════════════════════════════════════════╗
#  ║ ███████╗░█████╗░░█████╗░███╗░░██╗░█████╗░███╗░░░███╗██╗░░░██╗██████╗░██╗░░░░░██╗░░░██╗░██████╗ ║
#  ║ ██╔════╝██╔══██╗██╔══██╗████╗░██║██╔══██╗████╗░████║╚██╗░██╔╝██╔══██╗██║░░░░░██║░░░██║██╔════╝ ║
#  ║ █████╗░░██║░░╚═╝██║░░██║██╔██╗██║██║░░██║██╔████╔██║░╚████╔╝░██████╔╝██║░░░░░██║░░░██║╚█████╗░ ║
#  ║ ██╔══╝░░██║░░██╗██║░░██║██║╚████║██║░░██║██║╚██╔╝██║░░╚██╔╝░░██╔═══╝░██║░░░░░██║░░░██║░╚═══██╗ ║
#  ║ ███████╗╚█████╔╝╚█████╔╝██║░╚███║╚█████╔╝██║░╚═╝░██║░░░██║░░░██║░░░░░███████╗╚██████╔╝██████╔╝ ║
#  ║ ╚══════╝░╚════╝░░╚════╝░╚═╝░░╚══╝░╚════╝░╚═╝░░░░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚══════╝░╚═════╝░╚═════╝░ ║
#  ╚════════════════════════════════════════════════════════════════════════════════════════════════╝

# EconomyPlus made by _ItsWagPvP
# Watch the full resource on https://github.com/ItsWagPvP/EconomyPlus

# Do not change this!
# This is used to verify your config version
Version: ${project.version}

# Languages are stored in the EconomyPlus/messages folder.
# Credit to translaters for the assistance in creating these languages.
# Available Languages include: EN, IT, RO, AL, DE, ZH, FR, RU, ES
Language: EN

# bStats system (https://bstats.org/plugin/bukkit/EconomyPlus/11565)
Metrics: true

# It will send to console plugin's internal logs
Debug-Mode: false

# Controls if EconomyPlus need to connect to another plugin for more features
Hooks:
  # Placeholders
  PlaceholderAPI: true
  HolographicDisplays: true

# You want to enable the updater?
# This will enable the update checker and alert you on new updates in console.
Updater: true

# You will receive update notifications in game when you join if you have the permission (economyplus.update)
Updater-Notifications: true

# Use permissions for commands not including administrative commands?
# If false, Permission are not required for commands listed below
# /pay, /paytoggle, /bal, /bal <others>, /baltop, /bank, /bank deposit & /bank withdraw
Use-Permissions: true

# Adds Use-Permissions option which allows user to remove the need for permission on specific default commands including:
# Play to the player the sounds in front of success / error
Sounds:
  Use: true
  Success: ENTITY_PLAYER_LEVELUP
  Error: ENTITY_VILLAGER_NO

Use-Decimals: true # If true it's 0.00, if false is 0
Remove-Naughts: true # 10.0 > 10   12,402.00 > 12,402   10.03 > 10.03
Rounding: false # 10.005 = 10.01, if false: 10.005 = 10.00 (RECOMMENDED FALSE)

# This will work only with %money% and not with %money_formatted%
# This affects baltop and balances globally
Pattern:
  Enabled: true
  Value: "###,###.##"

# Used to format the %economyplus_money_formatted% placeholder
# 1000 = 1k
# 1000000 = 1M
# 1000000000 = 1B
# 1000000000000 = 1T
# 1000000000000000 = 1Q
Format:
  k: "k"
  M: "M"
  B: "B"
  T: "T"
  Q: "Q"

# Set a user balance on join
Starting-Balance: 0

# Set a user bank on join
Starting-Bank-Balance: 0

# Baltop configuration
Baltop:
  Chat:
    # Like 1) _ItsWagPvP: $100
    Player-Format: "&6%number%) &f%player%: &c$%money%"
    # The header of /baltop
    Header:
      - '&8&m-----------------'
      - '&d&lBalTop (Page %page%)'
      - '&8&m-----------------'
  # This is for the hologram! (/ep hologram)
  Hologram:
    # Refresh rate of holograms!
    Refresh-Rate: 60 # <- In seconds
    Player-Format: "&6%number%) &f%player%: &c$%money%"
    Header:
      - '&8&m-----------------'
      - '&d&lBalTop'
      - '&8&m-----------------'

# Select how to storage the data
Database:
  # Cache settings for better db performances
  Cache:
    # How much frequently the plugin should refresh the cache?
    # Does not affect player moneys or placeholders
    # It's only for security purposes
    # Default: 300 = 5 Minutes
    Auto-Save: 300 # <- In seconds
    # How many frequently the cache needs to be
    # refreshed with the MySQL db?
    MySQL: 10 # <- In seconds
  # You can choose one from UUID or NICKNAME
  Mode: "UUID"
  # H2 (database.db)
  # MySQL
  # YAML (data.yml)
  Type: H2
  # If you have set Type to H2 or YAML you have to ignore this options
  # Localhost connection
  Host: localhost
  # Default is 3306
  Port: 3306
  # The user for use MySQL connection
  User: root
  # Password of the user
  Password: qwerty
  # Database name
  Database: EconomyPlus
  # If you have not set up the table the plugin will create it for you!
  Table: economy
  # If the plugin loses connection it will auto-reconnect to the database
  AutoReconnect: true
  # Using an SSL certificate?
  useSSL: false


# This is the section where you can customize the /bank command
Bank:
  # You want to use the bank feature?
  Enabled: true
  # Interests feature
  Interests:
    Enabled: true
    # How frequently the bank will add the interests?
    Time: 300 # <- In seconds!
    # Interest rate (%)
    Percentage: 10
    # The player needs to be online to receive the interest?
    Online-Player: false

# This is the section where you can customize URL Webhook Discord
DiscordWebhook:
  # Enabled discord webhook?
  Enabled: false
  # Below you can modify the Discord URL
  Url:
