name: EconomyPlus
version: ${project.version}
main: me.itswagpvp.economyplus.EconomyPlus
api-version: 1.13
authors: [ _ItsWagPvP ]
load: STARTUP
softdepend:
  - Vault
  - PlaceholderAPI
  - HolographicDisplays
commands:
  economyplus:
    aliases:
      - ep
    usage: /<command>
  eco:
    usage: /<command>
  bal:
    aliases:
      - balance
      - money
    usage: /<command>
  pay:
    usage: /<command>
  paytoggle:
    usage: /<command>
  baltop:
    usage: /<command>
    aliases:
      - balancetop
  bank:
    usage: /<command>
    